apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-sa
  namespace: example-ns
  annotations:
    # eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/bigquery-workload-identity-role"
    eks.amazonaws.com/role-arn: "<YOUR ROLE ARN>"